### ISSUE TITLE
auto array not working correctly

### ISSUE THREAD

**Issue by jm-mh** [aap/abc#1]
This test case generates bad code:

main() {
    auto a[10];
    a[1] = 1234;
    putnumb(a[1]);
}

**Comment by jm-mh** [comment]
Oops. No push access to outsiders.
I have fix in hand. 
1) In file b0.c, routine defvec(), edit the first printf() statement:
     old:   printf("\t%%esp,%%eax\n");
     new: printf("\tmov\t%%esp,%%eax\n");
2) In file b0.c, routine blkhed(), add the following after the call to defvec()
     new: bs->offset = al;

Regards,
jm-mh

**Comment by aap** [comment]
Thanks for catching that, applied your fix now. It's been a while since I've worked on this code so I just trust your patch works.
