### ISSUE TITLE
unary minus not working correctly

### ISSUE THREAD

**Issue by jm-mh** [aap/abc#2]
This test case generates bad code:

main() {
auto a,b;
a = -1;
b = -a;
putnumb(b);   /\* Should print the number 1 */
}

Current code prints a 0 for this test case.

**Comment by jm-mh** [comment]
I have fix in hand.
1) In file b1.c, routine rcexpr(), case NEG:,edit the printf() statement:
old: printf("\tnot\t%%eax\n");
new: printf("\tneg\t%%eax\n");
2) Do a 'make libs' to propagate this fix to lib.o

**Comment by aap** [comment]
Fixed.
