### ISSUE TITLE
Redistribution license?

### ISSUE THREAD

**Issue by davidgiven** [aap/abc#4]
Is there any chance of a license for this? I'd quite like to port it into the Amsterdam Compiler Kit (https://github.com/davidgiven/ack).

(If you didn't have any other opinions, something like MIT or BSD would be ideal.)

(Also, I believe we talked at vcfe.ch the other day...)

**Comment by aap** [comment]
It's MIT now. You may also be interested in this B compiler they wrote for the pdp-7 UNIX restoration project: https://github.com/DoctorWkt/pdp7-unix/blob/master/tools/b.c. Note that my solution to the word addressed memory was rather hacky (I explained it to you at vcfe): all addresses of all (byte) addresses are put into a special ELF section, then I loop over them and patch them to word addresses before calling main. Does your toolchain contain a linker as well? Maybe you can make it generate word addresses directly. Fun fact: the PDP-10 linker could evaluate arbitrary expressions by storing an RPN representation of them in the relocatable file.

**Comment by davidgiven** [comment]
Thank-you very much!

I see what you mean about the addresses; I hadn't realised how much additional complexity there was until looking at the code. I do have a linker, but it's not capable of modifying addresses like that, and unfortunately I don't think my intermediate code format supports sections (it's too high level for that).

I think I'm going to have to generate code to do the fixups, which is a shame as it adds a lot of complexity. (Actually converting the code generator, by comparison, is almost trivial.)

**Comment by davidgiven** [comment]
I have it working! At least up to the point of 'Hello, world'. I've tried i386, i86 and PowerPC, and they seem to be okay (that is, they all print 'Hello, world').

I'm using the same system you're using, except the compiler emits a table at the bottom of the file --- so you don't separate compilation, which is deeply unsatisfactory. Importing non-B functions is very hard, too. So I need to think about that.

If you're interested, it's here:

https://github.com/davidgiven/ack/tree/dtrg-b

Do 'make' to build, then:

    ACKDIR=/tmp/ack-build/staging /tmp/ack-build/staging/bin/ack -mlinux386 -.b inputfile.b

The only standard library functions are `char`, `lchar`, `getchar` and `putchar`.
