### ISSUE TITLE
Variables used as function pointers are coerced to externs

### ISSUE THREAD

**Issue by davidgiven** [aap/abc#5]
In this code:

    call(a) return a();

...the call to `a()` actually tries to look up an external called `a` rather than using the value of the parameter.

I believe the fix is to change the code at the top of `tree()` from this:

	case NAME:
		if (pushsym(symbol()) == LPARN) {	/* function */
			bsym->class = EXTERN;
		}

to this:

	case NAME:
		if (pushsym(symbol()) == LPARN) {	/* function */
			if (bsym->class == 0)
				bsym->class = EXTERN;
		}

...so that only undeclared symbols get imported as externs.

**Comment by aap** [comment]
Yeah, that looks good. Fixed it, thanks.
