### ISSUE TITLE
forward gotos not working correctly

### ISSUE THREAD

**Issue by jm-mh** [aap/abc#6]
This test case generates bad code::

    main() {
            auto c;
            c=1;
            if (c==1) goto okay;
            printf("bad");
            return;
    okay:
            printf("okay");
    }

Current code prints the message "bad".

**Comment by jm-mh** [comment]
I have fix in hand. These changes come from last1120c, files c00.c and c02.c

1. In file b0.c, routine statement(), case GOTO, insert 2 lines:

		case GOTO:
			if ((o = symbol()) != NAME)
				goto syntax;
			if (bsym->offset == 0) /* unseen so far */          /* INSERT */
				bsym->offset = isn++;                       /* INSERT */
			jump(bsym->offset);
			goto semi;

2. In file b0.c, routine statement(), case NAME, insert 1 line and indent 1 line:

    	case NAME:
    		if (peekc == ':') {
    			peekc = 0;
    			if (bsym->class) {
    				error("Redefinition");
    				goto stmt;
    			}
    			bsym->class = INTERN;
    			if (bsym->offset == 0)                       /* INSERT */
    				bsym->offset = isn++;                /* INDENT */
    			label(bsym->offset);
    			goto stmt;

Regards,
Jeff

**Comment by aap** [comment]
Fixed, thanks!
